name: Deploy Static Files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > .env
        echo "DEBUG=False" >> .env
        
    - name: Collect Static Files
      run: python manage.py collectstatic --noinput
      env:
        DJANGO_SETTINGS_MODULE: django_chatbot.settings
        
    - name: Create index.html
      run: |
        mkdir -p staticfiles
        echo "<html><head><title>Django Chatbot</title></head><body><h1>Django Chatbot</h1><p>This is a static page for the Django Chatbot project.</p></body></html>" > staticfiles/index.html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./staticfiles
        enable_jekyll: false
